eureka:
  client:
    service-url:
      defaultZone: http://42.194.215.243:10086/eureka/
    registry-fetch-interval-seconds: 1
  instance:
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true # 当你获取host时，返回的不是主机名，而是ip
    ip-address: 42.194.215.243
ribbon:
  ConnectTimeout: 20000 # 连接超时时间(ms)
  ReadTimeout: 30000 # 通信超时时间(ms)
  OkToRetryOnAllOperations: true # 是否对所有操作重试
  MaxAutoRetriesNextServer: 3 # 同一服务不同实例的重试次数
  MaxAutoRetries: 3 # 同一实例的重试次数
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMillisecond: 60000 # 熔断超时时长：10000ms
